---
- name: Install dependency packages
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
  tags:
    - nginx

- name: Import GPG-key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  tags:
    - nginx

- name: Add Nginx repo
  apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx
  tags:
    - nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  tags:
    - nginx

- name: Copy *.conf file for nginx
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: Start nginx service
  tags:
    - nginx
